# Generated by Django 4.1.3 on 2022-12-07 20:31

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import impressions.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(x=56.01416977236943, y=92.85782247644305), srid=4326, validators=[impressions.validators.long_lat_validator])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
