# Generated by Django 4.1.3 on 2022-12-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='backend_name',
            field=models.TextField(default=''),
        ),
    ]
