# Generated by Django 4.1.3 on 2022-12-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_backend_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='backend_name',
            field=models.TextField(default='google-oauth2'),
        ),
    ]
