# Generated by Django 4.1.3 on 2022-12-03 06:43

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(56.01416977236943, 92.85782247644305), srid=4326),
        ),
    ]
