# Generated by Django 4.1.3 on 2022-12-03 12:09

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_place_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(x=56.01416977236943, y=92.85782247644305), srid=4326),
        ),
    ]
