# Generated by Django 4.1.3 on 2022-12-04 07:40

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(x=92.85782247644305, y=56.01416977236943), srid=4326),
        ),
    ]
